locations:
  !include config/locations/redmi.yaml

waits:
  !include config/waits/redmi.yaml

blacklist:
  -
  #disabled because of https://github.com/Azelphur/PokemonGo-CalcyIV-Renamer/issues/47
  #!include config/blacklist.yaml


## Select below which action file you'd like to use:
#  default:   for main acc
#  alt:       for alt acc
#  prettify:  for main after renaming with default.
#               howto: filter by * and run this
#  trade:     for main and alt *after* trading lots of pokes.
#               howto: filter by 'trade' and run this
#  unown:     for main after renaming with default.
#               howto: filter by 'unown' and run this.
## *Take a look at those yamls yourself, so you understand better how this works*
actions:
  !include config/actions/default.yaml


## How trading symbols (should, threoretically) work:
# π is for safe trading (automated, shouldn't trade anything special)
# Ω is for evo pokes (for using lucky egg). You can trade them for candy,
#   alongside π, and then evolve the already traded ones! :D
# μ are not-that-safe pokemons for auto-trading. I'd advise trading π for π only, so it's fair.
