- Larvitar
- Pupitar

- Dratini
- Dragonair

- Chansey

- Munchlax

- Bagon
- Shelgon

- Beldum
- Metang

- Ralts
- Kirlia

- Slakoth
- Vigoroth

- Marowak Alolan
- Mawile
- Absol
- Porygon
- Lickitung
- Pineco
- Trapinch
- Cranidos
- Shieldon

## You can delete pokemons above, but I guess most people
## would agree that those are good pokes to trade for extra
## candies. nom nom nom

## Add your own below.. or above, whatever floats your boat :D
- Meowth Alolan
- Vulpix Alolan
- Grimer Alolan
- Sandshrew Alolan
